name: less_projects
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  equatable: ^1.2.0
  flutter_bloc: ^4.0.0
  firebase_auth: ^0.16.0
  http: ^0.12.1
  cached_network_image: ^2.2.0+1
  url_launcher: ^5.4.10


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/social-media.png
   - images/add_user.png

   - images/10_nigret.jpg
   - images/bezmolv_pacient.jpg
   - images/face_with_shram.jpg
   - images/five_five.jpg
   - images/girl_in_train.webp
   - images/i_find_you.jpg
   - images/sherlok_holmse.jpg
   - images/telefonist.jpg
   - images/the_one.jpg
   - images/dnk_geniya.jpg

   - images/harry.jpg
   - images/harry1.png
   - images/harry2.jpeg
   - images/20_tis_lye_pod_vodoy.jpg
   - images/beliy_klik.jpg
   - images/dva_capitana.jpg
   - images/tainstven_ostrov.jpg
   - images/tri_mushketera.jpg
   - images/dvacyat_let_spustya.jpg
   - images/deti_kapitana_granta.jpg

   - images/1984.jpg
   - images/jack_london.jpg
   - images/451_po_fareng.jpg
   - images/belaya_gvardiya.jpg
   - images/finansist.jpg
   - images/kriscniy_otec.jpg
   - images/morskoy_volk.jpg
   - images/nad_propastyu_vo_rzi.jpg
   - images/zov_predkov.jpg
   - images/vsadnic_bez_golovi.jpg

   - images/piraty_karibskogo_morya.jpg
   - images/ZooTropolis.jpg
   - images/Avengers.webp
   - images/leon_king1.webp
   - images/harry_1.webp
   - images/briliantovaya_ruka.webp
   - images/toy_story1.webp
   - images/sherlok.webp
   - images/fantasticheskiye_tvari_1.webp
   - images/marsianin.webp

   - images/nachalo.webp
   - images/ivan_vasilievich.webp
   - images/avatar.webp
   - images/temniy_ricar.webp
   - images/matrix.webp
   - images/strazi_galaktiki.webp
   - images/valee.webp
   - images/back_to_future.webp
   - images/five_elem.webp
   - images/deadpool.webp

   - images/odin_doma.webp
   - images/hatico.webp
   - images/golovolomka.webp
   - images/malefisenta.webp
   - images/cars.webp
   - images/chudo.webp
   - images/paddingtons_advanture.webp
   - images/polosatiy_reys.webp
   - images/prizrak.webp
   - images/101_dalmatines.webp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the a sset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto-Thin
      fonts:
        - asset:  fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
          # style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
